/**
 * models/tracksData.js
 * ──────────────────────────────────────────────────────────────
 * In-memory track repository containing all core & archive tracks.
 */

const TRACKS = [
  /* ─ Side A ─ */
  {
    id: 1,
    title: 'Teri Yaad (Extended Mix)',
    artist: 'Ram Radio Sessions',
    album: 'Vol. 01 — Golden Hours',
    cover: null,
    audioUrl: '/audio/teri-yaad.mp3',
    duration: 263,
    genre: 'Indie / Cassette',
    year: 1987,
    side: 'A',
    num: '01',
    description: 'Master reel recorded live in Chandni Chowk.',
  },
  {
    id: 2,
    title: 'Gully Nights',
    artist: 'Ram Radio Sessions',
    album: 'Vol. 01 — Golden Hours',
    cover: null,
    audioUrl: '/audio/gully-nights.mp3',
    duration: 225,
    genre: 'Ambient / Street',
    year: 1988,
    side: 'A',
    num: '02',
    description: 'Nocturnal field recording with tape echo.',
  },
  {
    id: 3,
    title: 'Cassette Rain',
    artist: 'Ram Radio Sessions',
    album: 'Vol. 01 — Golden Hours',
    cover: null,
    audioUrl: '/audio/cassette-rain.mp3',
    duration: 312,
    genre: 'Instrumental',
    year: 1989,
    side: 'A',
    num: '03',
    description: 'Rooftop monsoon ambience and acoustic guitar.',
  },
  {
    id: 4,
    title: 'Radio Silence',
    artist: 'Ram Radio Sessions',
    album: 'Vol. 01 — Golden Hours',
    cover: null,
    audioUrl: '/audio/radio-silence.mp3',
    duration: 238,
    genre: 'Drone / Ambient',
    year: 1986,
    side: 'A',
    num: '04',
    description: 'Off-air frequency bleed between radio stations.',
  },
  /* ─ Side B ─ */
  {
    id: 5,
    title: 'Street Echoes',
    artist: 'Ram Radio Sessions',
    album: 'Vol. 01 — Golden Hours',
    cover: null,
    audioUrl: '/audio/street-echoes.mp3',
    duration: 250,
    genre: 'Indie / Cassette',
    year: 1990,
    side: 'B',
    num: '01',
    description: 'Vintage cassette deck playback from narrow alleys.',
  },
  {
    id: 6,
    title: 'Golden Hours',
    artist: 'Ram Radio Sessions',
    album: 'Vol. 01 — Golden Hours',
    cover: null,
    audioUrl: '/audio/golden-hours.mp3',
    duration: 362,
    genre: 'Jazz / Fusion',
    year: 1988,
    side: 'B',
    num: '02',
    description: 'Sunset fusion piece with warm sax and tablas.',
  },
  {
    id: 7,
    title: 'Late Night Raga',
    artist: 'Ram Radio Sessions',
    album: 'Vol. 01 — Golden Hours',
    cover: null,
    audioUrl: '/audio/late-night-raga.mp3',
    duration: 284,
    genre: 'Classical / Fusion',
    year: 1985,
    side: 'B',
    num: '03',
    description: 'Midnight sitar improvisation with analog flutter.',
  },
  {
    id: 8,
    title: 'The Last Station',
    artist: 'Ram Radio Sessions',
    album: 'Vol. 01 — Golden Hours',
    cover: null,
    audioUrl: '/audio/last-station.mp3',
    duration: 333,
    genre: 'Ambient / Closing',
    year: 1991,
    side: 'B',
    num: '04',
    description: 'Empty railway platform recording after the last train.',
  },
]

module.exports = TRACKS
