/**
 * models/tracksData.js
 * ──────────────────────────────────────────────────────────────
 * Centralized track repository supporting custom added tracks.
 */

const TRACKS = [
  {
    id: 'track-heer',
    title: 'Heer',
    artist: 'Ali Raza Shjr',
    album: 'Gully Radio Special Archives',
    cover: null,
    audioUrl: '/audio/Heer_-_Ali_Raza_Shjr_Lyrics.mp3',
    duration: 251,
    genre: 'Sufi / Folk',
    year: 2024,
    mood: 'Late Night',
    language: 'Punjabi',
    description: 'Poetic folk masterpiece recorded with acoustic resonance.',
    featured: true,
    recentlyAdded: true,
    trending: true,
  },
  {
    id: 'track-001',
    title: 'Teri Yaad (Extended Mix)',

    artist: 'Ram Radio Sessions',
    album: 'Vol. 01 — Golden Hours',
    cover: '/assets/album-art/song-01.jpg',
    audioUrl: '/audio/song-01.mp3',
    duration: 263,
    genre: 'Indie',
    year: 1987,
    mood: 'Late Night',
    language: 'Hindi',
    description: 'Master reel recorded live in Chandni Chowk.',
    featured: true,
    recentlyAdded: true,
    trending: true,
  },
  {
    id: 'track-002',
    title: 'Gully Nights',
    artist: 'Ram Radio Sessions',
    album: 'Vol. 01 — Golden Hours',
    cover: '/assets/album-art/song-02.jpg',
    audioUrl: '/audio/song-02.mp3',
    duration: 225,
    genre: 'Ambient',
    year: 1988,
    mood: 'Late Night',
    language: 'Hindi',
    description: 'Nocturnal field recording with tape echo.',
    featured: true,
    recentlyAdded: true,
    trending: true,
  },
  {
    id: 'track-003',
    title: 'Cassette Rain',
    artist: 'Ram Radio Sessions',
    album: 'Vol. 01 — Golden Hours',
    cover: '/assets/album-art/song-03.jpg',
    audioUrl: '/audio/song-03.mp3',
    duration: 312,
    genre: 'Instrumental',
    year: 1989,
    mood: 'Chill',
    language: 'Instrumental',
    description: 'Rooftop monsoon ambience and acoustic guitar.',
    featured: false,
    recentlyAdded: true,
    trending: true,
  },
  {
    id: 'track-004',
    title: 'Radio Silence',
    artist: 'Ram Radio Sessions',
    album: 'Vol. 01 — Golden Hours',
    cover: null,
    audioUrl: null,
    duration: 238,
    genre: 'Ambient',
    year: 1986,
    mood: 'Late Night',
    language: 'Instrumental',
    description: 'Off-air frequency bleed between radio stations.',
    featured: false,
    recentlyAdded: false,
    trending: false,
  },
  {
    id: 'track-005',
    title: 'Chandni Chowk 03:00 AM',
    artist: 'Ram Radio Sessions',
    album: 'Vol. 01 — Golden Hours',
    cover: null,
    audioUrl: null,
    duration: 194,
    genre: 'Indie',
    year: 1987,
    mood: 'Late Night',
    language: 'Hindi',
    description: 'Late night passing freight train and street whistle.',
    featured: false,
    recentlyAdded: false,
    trending: true,
  },
  {
    id: 'track-006',
    title: 'Golden Hours',
    artist: 'Ram Radio Sessions',
    album: 'Vol. 01 — Golden Hours',
    cover: null,
    audioUrl: null,
    duration: 362,
    genre: 'Indie',
    year: 1988,
    mood: 'Chill',
    language: 'Hindi',
    description: 'Sunset fusion piece with warm instruments.',
    featured: true,
    recentlyAdded: false,
    trending: true,
  },
  {
    id: 'track-007',
    title: 'Late Night Raga',
    artist: 'Ram Radio Sessions',
    album: 'Vol. 01 — Golden Hours',
    cover: null,
    audioUrl: null,
    duration: 284,
    genre: 'Instrumental',
    year: 1985,
    mood: 'Nostalgic',
    language: 'Instrumental',
    description: 'Midnight sitar improvisation with analog flutter.',
    featured: false,
    recentlyAdded: false,
    trending: false,
  },
  {
    id: 'track-008',
    title: 'Last Train Home',
    artist: 'Ram Radio Sessions',
    album: 'Vol. 01 — Golden Hours',
    cover: null,
    audioUrl: null,
    duration: 297,
    genre: 'Ambient',
    year: 1990,
    mood: 'Nostalgic',
    language: 'Hindi',
    description: 'Empty railway platform recording after the last train.',
    featured: false,
    recentlyAdded: false,
    trending: true,
  },
]

module.exports = TRACKS
